import {
    StyleSheet,
    Dimensions,
} from "react-native";

import { spacing, borderRadius } from "../../lib/colors";
const { width, height } = Dimensions.get("window");


export const getStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: theme.background,
        gap: spacing.md,
    },
    loadingText: {
        color: theme.textMuted,
        fontSize: 16,
        fontWeight: "500",
    },
    emptyContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: theme.background,
        padding: spacing.xl,
    },
    emptyTitle: {
        color: theme.text,
        fontSize: 22,
        fontWeight: "bold",
        marginTop: spacing.lg,
    },
    emptySubtitle: {
        color: theme.textMuted,
        fontSize: 14,
        textAlign: "center",
        marginTop: spacing.sm,
        marginBottom: spacing.xl,
        lineHeight: 20,
    },
    reloadButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.pink,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.xl,
        borderRadius: borderRadius.lg,
        minWidth: 180,
        elevation: 3,
        shadowColor: theme.pink,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    reloadButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "600",
    },

    swiperContainer: {
        flex: 1,
        marginTop: 30,
    },
    card: {
        borderWidth: 0.5,
        borderColor: "rgba(255,255,255,0.1)",
        elevation: 4,
        height: height * 0.59,
        borderRadius: borderRadius.xl,
        overflow: "hidden",
        backgroundColor: theme.surface,
    },
    cardImage: {
        width: "100%",
        height: "100%",
        resizeMode: "cover",
    },
    cardGradient: {
        position: "absolute",
        left: 0,
        right: 0,
        bottom: 0,
        height: "60%",
        justifyContent: "flex-end",
        padding: spacing.lg,
    },
    cardContent: {
        gap: spacing.sm,
    },
    cardHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.sm,
    },
    cardName: {
        fontSize: 28,
        fontWeight: "bold",
        color: theme.isLightTheme? "white" :theme.text,
    },
    cardInfo: {
        gap: spacing.xs,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.xs,
    },
    infoText: {
        color: theme.textMuted,
        fontSize: 14,
    },
    goalBadge: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(236, 72, 153, 0.25)",
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        borderRadius: borderRadius.sm,
        alignSelf: "flex-start",
        gap: spacing.xs,
    },
    goalText: {
        color: theme.text,
        fontSize: 12,
        fontWeight: "500",
    },
    tagsSection: {
        marginTop: spacing.xs,
    },
    tagHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: spacing.xs,
        marginBottom: spacing.xs,
    },
    tagLabel: {
        color: theme.textMuted,
        fontSize: 12,
    },
    tagsRow: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: spacing.xs,
    },
    tag: {
        backgroundColor: "rgba(255,255,255,0.12)",
        paddingHorizontal: spacing.sm,
        paddingVertical: 5,
        borderRadius: borderRadius.sm,
    },
    studyTag: {
        backgroundColor: "rgba(99, 102, 241, 0.25)",
    },
    tagText: {
        color: theme.text,
        fontSize: 12,
    },
    actionButtons: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: spacing.lg,
        position: "absolute",
        bottom: 20,
        left: 0,
        right: 0,
        zIndex: 100,
    },
    dislikeButton: {
        width: 60,
        height: 60,
        borderRadius: 32,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
    },
    likeButton: {
        width: 68,
        height: 68,
        borderRadius: 38,
        overflow: "hidden",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
    },
    likeButtonGradient: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    mutationLoader: {
        position: "absolute",
        zIndex: 150,
        backgroundColor: "rgba(255,255,255,0.9)",
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        elevation: 6,
    },
    overlayLabelLeft: {
        fontSize: 32,
        fontWeight: "bold",
        color: theme.error,
        borderWidth: 4,
        borderColor: theme.error,
        borderRadius: borderRadius.md,
        padding: spacing.sm,
        backgroundColor: "rgba(239, 68, 68, 0.15)",
    },
    overlayWrapperLeft: {
        flexDirection: "column",
        alignItems: "flex-end",
        justifyContent: "flex-start",
        marginTop: 80,
        marginRight: 20,
    },
    overlayLabelRight: {
        fontSize: 32,
        fontWeight: "bold",
        color: theme.success,
        borderWidth: 4,
        borderColor: theme.success,
        borderRadius: borderRadius.md,
        padding: spacing.sm,
        backgroundColor: "rgba(34, 197, 94, 0.15)",
    },
    overlayWrapperRight: {
        flexDirection: "column",
        alignItems: "flex-start",
        justifyContent: "flex-start",
        marginTop: 80,
        marginLeft: 20,
    },
});