import {
    StyleSheet,
} from "react-native";
import { colors, spacing, borderRadius } from "@/lib/colors";


export const getStyles = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
        paddingHorizontal: spacing.md,
        paddingTop: 20,
    },
    searchBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: theme.surface,
        paddingHorizontal: spacing.md,
        paddingVertical: 4,
        borderRadius: borderRadius.lg,
        gap: 10,
        marginBottom: 2,
        borderWidth: 0.6,
        borderColor: theme.border,
    },
    input: {
        flex: 1,
        color: theme.text,
        fontSize: 15,
    },
    list: {
        paddingTop: spacing.md,
        paddingBottom: 100,
    },
    randomCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: theme.surfaceLight,
        paddingVertical: spacing.sm,
        paddingHorizontal: spacing.sm + 4,
        borderRadius: borderRadius.xl,
        marginBottom: spacing.md,
        borderWidth: 1,
        borderColor: theme.border,
        gap: 12,
    },
    randomIconWrap: {
        width: 42,
        height: 42,
        borderRadius: 12,
        backgroundColor: theme.primary,
        alignItems: "center",
        justifyContent: "center",
    },
    randomTitle: {
        color: theme.text,
        fontSize: 15,
        fontWeight: "800",
    },
    randomSub: {
        color: theme.textMuted,
        fontSize: 12,
        marginTop: 2,
    },
    card: {
        backgroundColor: theme.surface,
        borderRadius: borderRadius.xl,
        padding: spacing.md,
        marginBottom: spacing.md,
        borderWidth: 1,
        borderColor: theme.border,
    },
    cardHeaderRow: {
        flexDirection: "row",
        gap: 14,
        alignItems: "center",
    },
    avatar: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: theme.surfaceLight,
    },
    info: {
        flex: 1,
    },
    name: {
        color: theme.text,
        fontSize: 14,
        fontWeight: "800",
        marginBottom: 2,
    },
    metaRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginTop: 2,
    },
    metaText: {
        color: theme.textMuted,
        fontSize: 12,
        flex: 1,
    },
    bottomActions: {
        flexDirection: "row",
        marginTop: spacing.md,
        gap: 10,
    },
    viewBtn: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: theme.surfaceLight,
        paddingVertical: 10,
        borderRadius: borderRadius.lg,
        gap: 6,
    },
    viewText: {
        color: theme.text,
        fontWeight: "600",
        fontSize: 14,
    },
    addBtn: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: theme.secondary,
        paddingVertical: 10,
        borderRadius: borderRadius.lg,
        gap: 6,
    },
    addText: {
        color: "white",
        fontWeight: "700",
        fontSize: 14,
    },
    friendsBtn: {
        backgroundColor: theme.surfaceLight,
        borderWidth: 1,
        borderColor: theme.border,
    },
    friendsText: {
        color: theme.textMuted,
        fontWeight: "700",
        fontSize: 14,
    },
    empty: {
        alignItems: "center",
        marginTop: 100,
        paddingHorizontal: 20,
    },
    emptyTitle: {
        color: theme.text,
        fontSize: 16,
        fontWeight: "700",
        marginTop: 10,
    },
    emptySub: {
        color: theme.textMuted,
        textAlign: "center",
        marginTop: 5,
        fontSize: 14,
    },
    exploreShortcut: {
        marginTop: 20,
        backgroundColor: theme.surfaceLight,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: borderRadius.lg,
        borderWidth: 1,
        borderColor: theme.border,
    },
    exploreShortcutText: {
        color: theme.text,
        fontWeight: "600",
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        marginTop: 100,
    },
    loadingText: {
        color: theme.textMuted,
        marginTop: 10,
        fontSize: 14,
    },
    emptyResults: {
        alignItems: "center",
        paddingVertical: 40,
    },
});